using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRC.WebPortal.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddOwnershipOnly : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Add OwnershipStatus column to Units table if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_schema = 'crc_webportal' 
                                   AND table_name = 'Units' 
                                   AND column_name = 'OwnershipStatus') THEN
                        ALTER TABLE crc_webportal.""Units"" ADD COLUMN ""OwnershipStatus"" character varying(20) NOT NULL DEFAULT 'Available';
                    END IF;
                END $$;
            ");

            // Create UnitOwnerships table if it doesn't exist
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS crc_webportal.""UnitOwnerships"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""OwnerName"" character varying(100) NOT NULL,
                    ""OwnerEmail"" character varying(100) NOT NULL,
                    ""OwnerMobile"" character varying(20) NOT NULL,
                    ""SellingDetails"" character varying(500),
                    ""SalePrice"" numeric(18,2),
                    ""SaleDate"" timestamp with time zone,
                    ""SaleStatus"" character varying(50) NOT NULL DEFAULT 'Sold',
                    ""UnitId"" integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
                    ""UpdatedAt"" timestamp with time zone,
                    ""CreatedBy"" text,
                    ""UpdatedBy"" text,
                    ""IsActive"" boolean NOT NULL DEFAULT true,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    ""RowVersion"" bytea,
                    CONSTRAINT ""PK_UnitOwnerships"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_UnitOwnerships_Units_UnitId"" FOREIGN KEY (""UnitId"") REFERENCES crc_webportal.""Units"" (""Id"") ON DELETE CASCADE
                );
            ");

            // Create indexes if they don't exist
            migrationBuilder.Sql(@"
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'crc_webportal' AND tablename = 'UnitOwnerships' AND indexname = 'IX_UnitOwnerships_UnitId') THEN
                        CREATE UNIQUE INDEX ""IX_UnitOwnerships_UnitId"" ON crc_webportal.""UnitOwnerships"" (""UnitId"");
                    END IF;
                    
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'crc_webportal' AND tablename = 'UnitOwnerships' AND indexname = 'IX_UnitOwnerships_OwnerEmail') THEN
                        CREATE INDEX ""IX_UnitOwnerships_OwnerEmail"" ON crc_webportal.""UnitOwnerships"" (""OwnerEmail"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS crc_webportal.""UnitOwnerships"";");
            migrationBuilder.Sql(@"ALTER TABLE crc_webportal.""Units"" DROP COLUMN IF EXISTS ""OwnershipStatus"";");
        }
    }
}
